window.countries = [
  { name: "Afghanistan", code: "+93", length: 9 },
  { name: "Albania", code: "+355", length: 9 },
  { name: "Algeria", code: "+213", length: 9 },
  { name: "Argentina", code: "+54", length: 10 },
  { name: "Australia", code: "+61", length: 9 },
  { name: "Austria", code: "+43", length: 10 },
  { name: "Belgium", code: "+32", length: 9 },
  { name: "Brazil", code: "+55", length: 11 },
  { name: "Bulgaria", code: "+359", length: 9 },
  { name: "Canada", code: "+1", length: 10 },
  { name: "Chile", code: "+56", length: 9 },
  { name: "China", code: "+86", length: 11 },
  { name: "Colombia", code: "+57", length: 10 },
  { name: "Croatia", code: "+385", length: 9 },
  { name: "Czech Republic", code: "+420", length: 9 },
  { name: "Denmark", code: "+45", length: 8 },
  { name: "Egypt", code: "+20", length: 10 },
  { name: "Finland", code: "+358", length: 10 },
  { name: "France", code: "+33", length: 9 },
  { name: "Germany", code: "+49", length: 11 },
  { name: "Greece", code: "+30", length: 10 },
  { name: "Hungary", code: "+36", length: 9 },
  { name: "Iceland", code: "+354", length: 7 },
  { name: "India", code: "+91", length: 10 },
  { name: "Indonesia", code: "+62", length: 10 },
  { name: "Ireland", code: "+353", length: 9 },
  { name: "Israel", code: "+972", length: 9 },
  { name: "Italy", code: "+39", length: 10 },
  { name: "Japan", code: "+81", length: 10 },
  { name: "Kenya", code: "+254", length: 9 },
  { name: "Malaysia", code: "+60", length: 9 },
  { name: "Mexico", code: "+52", length: 10 },
  { name: "Netherlands", code: "+31", length: 9 },
  { name: "New Zealand", code: "+64", length: 9 },
  { name: "Norway", code: "+47", length: 8 },
  { name: "Pakistan", code: "+92", length: 10 },
  { name: "Poland", code: "+48", length: 9 },
  { name: "Portugal", code: "+351", length: 9 },
  { name: "Romania", code: "+40", length: 9 },
  { name: "Russia", code: "+7", length: 10 },
  { name: "Singapore", code: "+65", length: 8 },
  { name: "Slovakia", code: "+421", length: 9 },
  { name: "Slovenia", code: "+386", length: 8 },
  { name: "South Africa", code: "+27", length: 9 },
  { name: "South Korea", code: "+82", length: 10 },
  { name: "Spain", code: "+34", length: 9 },
  { name: "Sweden", code: "+46", length: 9 },
  { name: "Switzerland", code: "+41", length: 9 },
  { name: "Thailand", code: "+66", length: 9 },
  { name: "Turkey", code: "+90", length: 10 },
  { name: "Ukraine", code: "+380", length: 9 },
  { name: "United Arab Emirates", code: "+971", length: 9 },
  { name: "United Kingdom", code: "+44", length: 10 },
  { name: "United States", code: "+1", length: 10 },
  { name: "Vietnam", code: "+84", length: 9 }
];
