window.countries = [
  { name: "Afghanistan", code: "+93", length: 9 },
  { name: "Albania", code: "+355", length: 8 },
  { name: "Algeria", code: "+213", length: 9 },
  { name: "American Samoa", code: "+1-684", length: 7 },
  { name: "Andorra", code: "+376", length: 6 },
  { name: "Angola", code: "+244", length: 9 },
  { name: "Antigua and Barbuda", code: "+1-268", length: 7 },
  { name: "Argentina", code: "+54", length: 10 },
  { name: "Armenia", code: "+374", length: 8 },
  { name: "Aruba", code: "+297", length: 7 },
  { name: "Australia", code: "+61", length: 9 },
  { name: "Austria", code: "+43", length: 9 },
  { name: "Azerbaijan", code: "+994", length: 9 },
  { name: "Bahamas", code: "+1-242", length: 7 },
  { name: "Bahrain", code: "+973", length: 8 },
  { name: "Bangladesh", code: "+880", length: 10 },
  { name: "Barbados", code: "+1-246", length: 7 },
  { name: "Belarus", code: "+375", length: 9 },
  { name: "Belgium", code: "+32", length: 9 },
  { name: "Belize", code: "+501", length: 7 },
  { name: "Benin", code: "+229", length: 8 },
  { name: "Bermuda", code: "+1-441", length: 7 },
  { name: "Bhutan", code: "+975", length: 8 },
  { name: "Bolivia", code: "+591", length: 8 },
  { name: "Bosnia and Herzegovina", code: "+387", length: 8 },
  { name: "Botswana", code: "+267", length: 8 },
  { name: "Brazil", code: "+55", length: 11 },
  { name: "Brunei", code: "+673", length: 7 },
  { name: "Bulgaria", code: "+359", length: 8 },
  { name: "Burkina Faso", code: "+226", length: 8 },
  { name: "Burundi", code: "+257", length: 8 },
  { name: "Cambodia", code: "+855", length: 8 },
  { name: "Cameroon", code: "+237", length: 8 },
  { name: "Canada", code: "+1", length: 10 },
  { name: "Cape Verde", code: "+238", length: 7 },
  { name: "Central African Republic", code: "+236", length: 8 },
  { name: "Chad", code: "+235", length: 8 },
  { name: "Chile", code: "+56", length: 9 },
  { name: "China", code: "+86", length: 11 },
  { name: "Colombia", code: "+57", length: 10 },
  { name: "Comoros", code: "+269", length: 7 },
  { name: "Costa Rica", code: "+506", length: 8 },
  { name: "Croatia", code: "+385", length: 9 },
  { name: "Cuba", code: "+53", length: 8 },
  { name: "Cyprus", code: "+357", length: 8 },
  { name: "Czech Republic", code: "+420", length: 9 },
  { name: "Denmark", code: "+45", length: 8 },
  { name: "Djibouti", code: "+253", length: 8 },
  { name: "Dominica", code: "+1-767", length: 7 },
  { name: "Dominican Republic", code: "+1-809", length: 10 },
  { name: "Ecuador", code: "+593", length: 10 },
  { name: "Egypt", code: "+20", length: 10 },
  { name: "El Salvador", code: "+503", length: 8 },
  { name: "Equatorial Guinea", code: "+240", length: 9 },
  { name: "Eritrea", code: "+291", length: 7 },
  { name: "Estonia", code: "+372", length: 7 },
  { name: "Eswatini", code: "+268", length: 8 },
  { name: "Ethiopia", code: "+251", length: 9 },
  { name: "Fiji", code: "+679", length: 7 },
  { name: "Finland", code: "+358", length: 9 },
  { name: "France", code: "+33", length: 9 },
  { name: "Gabon", code: "+241", length: 7 },
  { name: "Gambia", code: "+220", length: 7 },
  { name: "Georgia", code: "+995", length: 9 },
  { name: "Germany", code: "+49", length: 10 },
  { name: "Ghana", code: "+233", length: 9 },
  { name: "Greece", code: "+30", length: 10 },
  { name: "Greenland", code: "+299", length: 6 },
  { name: "Grenada", code: "+1-473", length: 7 },
  { name: "Guam", code: "+1-671", length: 10 },
  { name: "Guatemala", code: "+502", length: 8 },
  { name: "Guinea", code: "+224", length: 8 },
  { name: "Guinea-Bissau", code: "+245", length: 7 },
  { name: "Guyana", code: "+592", length: 7 },
  { name: "Haiti", code: "+509", length: 8 },
  { name: "Honduras", code: "+504", length: 8 },
  { name: "Hong Kong", code: "+852", length: 8 },
  { name: "Hungary", code: "+36", length: 8 },
  { name: "Iceland", code: "+354", length: 7 },
  { name: "India", code: "+91", length: 10 },
  { name: "Indonesia", code: "+62", length: 10 },
   { name: "Iran", code: "+98", length: 10 },
  { name: "Iraq", code: "+964", length: 10 },
  { name: "Ireland", code: "+353", length: 9 },
  { name: "Israel", code: "+972", length: 9 },
  { name: "Italy", code: "+39", length: 10 },
  { name: "Jamaica", code: "+1-876", length: 7 },
  { name: "Japan", code: "+81", length: 10 },
  { name: "Jordan", code: "+962", length: 9 },
  { name: "Kazakhstan", code: "+7", length: 10 },
  { name: "Kenya", code: "+254", length: 9 },
  { name: "Kiribati", code: "+686", length: 7 },
  { name: "Kuwait", code: "+965", length: 8 },
  { name: "Kyrgyzstan", code: "+996", length: 9 },
  { name: "Laos", code: "+856", length: 9 },
  { name: "Latvia", code: "+371", length: 8 },
  { name: "Lebanon", code: "+961", length: 8 },
  { name: "Lesotho", code: "+266", length: 8 },
  { name: "Liberia", code: "+231", length: 7 },
  { name: "Libya", code: "+218", length: 9 },
  { name: "Liechtenstein", code: "+423", length: 7 },
  { name: "Lithuania", code: "+370", length: 8 },
  { name: "Luxembourg", code: "+352", length: 8 },
  { name: "Macau", code: "+853", length: 8 },
  { name: "Madagascar", code: "+261", length: 9 },
  { name: "Malawi", code: "+265", length: 9 },
  { name: "Malaysia", code: "+60", length: 9 },
  { name: "Maldives", code: "+960", length: 7 },
  { name: "Mali", code: "+223", length: 8 },
  { name: "Malta", code: "+356", length: 8 },
  { name: "Marshall Islands", code: "+692", length: 7 },
  { name: "Mauritania", code: "+222", length: 8 },
  { name: "Mauritius", code: "+230", length: 8 },
  { name: "Mexico", code: "+52", length: 10 },
  { name: "Micronesia", code: "+691", length: 7 },
  { name: "Moldova", code: "+373", length: 8 },
  { name: "Monaco", code: "+377", length: 8 },
  { name: "Mongolia", code: "+976", length: 8 },
  { name: "Montenegro", code: "+382", length: 8 },
  { name: "Morocco", code: "+212", length: 9 },
  { name: "Mozambique", code: "+258", length: 9 },
  { name: "Myanmar", code: "+95", length: 9 },
  { name: "Namibia", code: "+264", length: 9 },
  { name: "Nauru", code: "+674", length: 7 },
  { name: "Nepal", code: "+977", length: 10 },
  { name: "Netherlands", code: "+31", length: 9 },
  { name: "New Zealand", code: "+64", length: 9 },
  { name: "Nicaragua", code: "+505", length: 8 },
  { name: "Niger", code: "+227", length: 8 },
  { name: "Nigeria", code: "+234", length: 10 },
  { name: "North Korea", code: "+850", length: 10 },
  { name: "North Macedonia", code: "+389", length: 8 },
  { name: "Norway", code: "+47", length: 8 },
  { name: "Oman", code: "+968", length: 8 },
  { name: "Pakistan", code: "+92", length: 10 },
  { name: "Palau", code: "+680", length: 7 },
  { name: "Palestine", code: "+970", length: 8 },
  { name: "Panama", code: "+507", length: 8 },
  { name: "Papua New Guinea", code: "+675", length: 7 },
  { name: "Paraguay", code: "+595", length: 9 },
  { name: "Peru", code: "+51", length: 9 },
  { name: "Philippines", code: "+63", length: 10 },
  { name: "Poland", code: "+48", length: 9 },
  { name: "Portugal", code: "+351", length: 9 },
  { name: "Qatar", code: "+974", length: 8 },
  { name: "Romania", code: "+40", length: 9 },
  { name: "Russia", code: "+7", length: 10 },
  { name: "Rwanda", code: "+250", length: 9 },
  { name: "Saint Kitts and Nevis", code: "+1-869", length: 7 },
  { name: "Saint Lucia", code: "+1-758", length: 7 },
  { name: "Saint Vincent and the Grenadines", code: "+1-784", length: 7 },
  { name: "Samoa", code: "+685", length: 7 },
  { name: "San Marino", code: "+378", length: 6 },
  { name: "Saudi Arabia", code: "+966", length: 9 },
  { name: "Senegal", code: "+221", length: 9 },
  { name: "Serbia", code: "+381", length: 8 },
  { name: "Seychelles", code: "+248", length: 7 },
  { name: "Sierra Leone", code: "+232", length: 7 },
  { name: "Singapore", code: "+65", length: 8 },
  { name: "Slovakia", code: "+421", length: 9 },
  { name: "Slovenia", code: "+386", length: 8 },
  { name: "Solomon Islands", code: "+677", length: 7 },
  { name: "Somalia", code: "+252", length: 8 },
  { name: "South Africa", code: "+27", length: 9 },
  { name: "South Korea", code: "+82", length: 10 },
  { name: "South Sudan", code: "+211", length: 9 },
  { name: "Spain", code: "+34", length: 9 },
  { name: "Sri Lanka", code: "+94", length: 9 },
  { name: "Sudan", code: "+249", length: 9 },
  { name: "Suriname", code: "+597", length: 7 },
  { name: "Sweden", code: "+46", length: 9 },
  { name: "Switzerland", code: "+41", length: 9 },
  { name: "Syria", code: "+963", length: 9 },
  { name: "Taiwan", code: "+886", length: 9 },
  { name: "Tajikistan", code: "+992", length: 9 },
  { name: "Tanzania", code: "+255", length: 9 },
  { name: "Thailand", code: "+66", length: 9 },
  { name: "Togo", code: "+228", length: 8 },
  { name: "Tonga", code: "+676", length: 7 },
  { name: "Trinidad and Tobago", code: "+1-868", length: 7 },
  { name: "Tunisia", code: "+216", length: 8 },
  { name: "Turkey", code: "+90", length: 10 },
  { name: "Turkmenistan", code: "+993", length: 8 },
  { name: "Tuvalu", code: "+688", length: 5 },
  { name: "Uganda", code: "+256", length: 9 },
  { name: "Ukraine", code: "+380", length: 9 },
  { name: "United Arab Emirates", code: "+971", length: 9 },
  { name: "United Kingdom", code: "+44", length: 10 },
  { name: "United States", code: "+1", length: 10 },
  { name: "Uruguay", code: "+598", length: 8 },
  { name: "Uzbekistan", code: "+998", length: 9 },
  { name: "Vanuatu", code: "+678", length: 7 },
  { name: "Vatican City", code: "+379", length: 6 },
  { name: "Venezuela", code: "+58", length: 10 },
  { name: "Vietnam", code: "+84", length: 9 },
  { name: "Yemen", code: "+967", length: 9 },
  { name: "Zambia", code: "+260", length: 9 },
  { name: "Zimbabwe", code: "+263", length: 9 }
];
